cartridge control scripts: Fix exit value handling
Fix some problems with how we handle exit values in control scripts.

Most control scripts have `#!/bin/bash -e` or `set -e` so that they exit
immediately if a command exits with a non-zero return value if that
command is not part of a compound command or conditional statement.
Thus if we anticipate that a command may fail, we must put it in a compound
command or a conditional statement.  This commit makes the following
changes:

• Replace `foo; [ $? -eq 0 ] && bar` with `local rc=0; foo || rc=$?;
  [[ "$rc" = 0 ]] && bar` where foo is an especially long command.

• Replace `foo; [ $? -eq 0 ] || bar` with `if ! foo; then bar; fi`.

• Replace `foo; ret=$?; if [ $ret -eq 0 ]; then` with `if foo; then`.

• Replace `foo; ret=$?; if [ $ret -ne 0 ]; then` with `if ! foo; then`.

• Replace `foo; bar $?` with `local rc=0; foo || rc=$?; bar "$rc"`.

• Replace `foo; return $?` with `local ret=0; foo || ret=$?; return
  $ret`.

• If a script runs with `/bin/bash -e` and ends with `exit $?`, delete
  the `exit $?` because it is redundant.

Moreover, several control scripts had inverted logic around the
/bin/kill command: These scripts would run /bin/kill, check its exit
value, and retry /bin/kill if the first attempt returned 0.  However,
an exit value of 0 from /bin/kill means that it succeeded, so this code
was retrying exactly when it did not need to do so.  This commit fixes
this logic.

diff --git a/cartridges/openshift-origin-cartridge-mongodb/bin/control b/cartridges/openshift-origin-cartridge-mongodb/bin/control
--- a/cartridges/openshift-origin-cartridge-mongodb/bin/control
+++ b/cartridges/openshift-origin-cartridge-mongodb/bin/control
@@ -39,8 +39,9 @@ function _repair_mongod() {
         client_result "Attempting to repair MongoDB ..."
         tmp_config="/tmp/mongodb.repair.conf"
         grep -ve "fork\s*=\s*true" $OPENSHIFT_MONGODB_DIR/conf/mongodb.conf > $tmp_config
-        mongodb_context "mongod ${authopts} -f ${tmp_config} --repair"
-        client_result "MongoDB repair status = $?"
+        local rc=0
+        mongodb_context "mongod ${authopts} -f ${tmp_config} --repair" || rc=$?
+        client_result "MongoDB repair status = $rc"
         rm -f $tmp_config
     else
         echo "MongoDB already running - not running repair"
@@ -84,16 +85,10 @@ function stop() {
 
     if [ -n "$pid" ]; then
         echo "Stopping MongoDB cartridge"
-        set +e
-        /bin/kill $pid 2>/dev/null
-        set -e
-        ret=$?
-        if [ $ret -eq 0 ]; then
+        if ! /bin/kill $pid 2>/dev/null; then
             TIMEOUT="$STOPTIMEOUT"
             while [ $TIMEOUT -gt 0 ] && [ -f "$OPENSHIFT_MONGODB_DIR/pid/mongodb.pid" ]; do
-                set +e
                 /bin/kill -0 "$pid" >/dev/null 2>&1 || break
-                set -e
                 sleep 1
                 let TIMEOUT=${TIMEOUT}-1
             done
@@ -125,8 +120,10 @@ function pre_snapshot {
    _wait_for_mongod_to_startup
    #  Work in a temporary directory (create and cd to it).
    umask 077
-   dumpdir=$(mktemp -d /tmp/mongodumpXXXXXXXX)
-   [ $? -eq 0 ] || die 0 "ERROR" "Failed to create working directory."
+   if ! dumpdir=$(mktemp -d /tmp/mongodumpXXXXXXXX)
+   then
+     die 0 "ERROR" "Failed to create working directory."
+   fi
    pushd $dumpdir > /dev/null
 
    #  Take a "dump".
@@ -187,8 +184,10 @@ WARNING: You may have possibly encountered the mongorestore bugs related to
 function restore_from_mongodb_snapshot {
    #  Work in a temporary directory (create and cd to it).
    umask 077
-   dumpdir=$(mktemp -d /tmp/mongodumpXXXXXXXX)
-   [ $? -eq 0 ] || die 0 "ERROR" "Failed to create working directory."
+   if ! dumpdir=$(mktemp -d /tmp/mongodumpXXXXXXXX)
+   then
+     die 0 "ERROR" "Failed to create working directory."
+   fi
    pushd $dumpdir > /dev/null
 
    #  Extract dump from the snapshot.
