distinguish between timed out and failed jboss starts

diff --git a/cartridges/openshift-origin-cartridge-jbosseap/bin/control b/cartridges/openshift-origin-cartridge-jbosseap/bin/control
--- a/cartridges/openshift-origin-cartridge-jbosseap/bin/control
+++ b/cartridges/openshift-origin-cartridge-jbosseap/bin/control
@@ -153,19 +153,22 @@ killtree() {
 
 # Check if the server http port is up
 function ishttpup() {
-
-    let count=0
+    count=0
     while [ ${count} -lt 64 ]
     do
         if /usr/sbin/lsof -P -n -i "@${OPENSHIFT_JBOSSEAP_IP}:${OPENSHIFT_JBOSSEAP_HTTP_PORT}" | grep "(LISTEN)" > /dev/null; then
             echo "Found ${OPENSHIFT_JBOSSEAP_IP}:${OPENSHIFT_JBOSSEAP_HTTP_PORT} listening port"
             return 0
         fi
+        # if the process failed to start, error out immediately
+        # rather than waiting for the timeout on the port being available.
+        if ! ps | grep -v grep | grep $PROCESS_ID > /dev/null; then
+          return 2
+        fi
         let count=${count}+1
 
         sleep 2
     done
-
     return 1
 }
 
@@ -285,11 +288,15 @@ function start() {
     PROCESS_ID=$!
     echo "$PROCESS_ID" > ${JBOSSEAP_PID_FILE}
 
-    if ! ishttpup; then
-      echo "Timed out waiting for http listening port"
+    rc=0
+    ishttpup || rc=$?
+    if [ $rc -eq 1 ]; then
+      echo "Timed out waiting for http listening port for $cartridge_type process"
       exit 1
+    elif [ $rc -eq 2 ]; then
+      echo "$cartridge_type process failed to start"
+      exit 2
     fi
-
     waitondeployments
   fi
 }
