Fix logic in set timeout.  Move the source_if_exists function to the top so any successive function can use it.  Add the arm timeout script.

diff --git a/stickshift/abstract/abstract/info/lib/util b/stickshift/abstract/abstract/info/lib/util
--- a/stickshift/abstract/abstract/info/lib/util
+++ b/stickshift/abstract/abstract/info/lib/util
@@ -4,6 +4,11 @@
 SS_CONTROLLER_LIB_UTIL=true
 source /etc/stickshift/stickshift-node.conf
 
+function source_if_exists {
+    [ -f "$1" ]  &&  source "$1"
+    return 0
+}
+
 function start_app {
     for env_var in  $APP_HOME/.env/*_CTL_SCRIPT
     do
@@ -53,11 +58,6 @@ function start_dbs {
     do
         $cmd start || error "Failed to start ${cmd}" 121
     done
-}
-
-function source_if_exists {
-    [ -f "$1" ]  &&  source "$1"
-    return 0
 }
 
 function get_app_type {
@@ -118,12 +118,26 @@ function create_standard_network_env_vars {
 
 function set_ctl_script_timeout {
   local timeout
-  if [ -z "$1" ]; then
+  if [ "$1" ]; then
     timeout="$1"
   else
-    timeout=30
+    timeout="30"
   fi
   echo "export OPENSHIFT_GEAR_CTL_TIMEOUT='$timeout'" > $APP_HOME/.env/OPENSHIFT_GEAR_CTL_TIMEOUT
+}
+
+function arm_ctl_script_timeout {
+  source_if_exists "$APP_HOME/.env/OPENSHIFT_GEAR_CTL_TIMEOUT"
+  
+  if [ "$OPENSHIFT_GEAR_CTL_TIMEOUT" ]; then
+    # Force integer comparison.  We want to fail here otherwise.
+    if [ "$OPENSHIFT_GEAR_CTL_TIMEOUT" -gt 0 ]; then
+      local ctl_pid ctl_time
+      ctl_pid=$$
+      ctl_time=$(( $(date '+%s') + $OPENSHIFT_GEAR_CTL_TIMEOUT ))
+      ( while [ $(date '+%s') -lt $ctl_time ]; do kill -s 0 $ctl_pid || exit 0 ; usleep 100000; done; kill $ctl_pid ) & </dev/null >/dev/null 2>&1
+    fi
+  fi
 }
 
 function create_standard_repo_dir_env_var {
