Attempt #2 to add MariaDB 5.5 support to RHEL from SCL based on recent MySQL Patch

diff --git a/cartridges/openshift-origin-cartridge-mariadb/bin/control b/cartridges/openshift-origin-cartridge-mariadb/bin/control
--- a/cartridges/openshift-origin-cartridge-mariadb/bin/control
+++ b/cartridges/openshift-origin-cartridge-mariadb/bin/control
@@ -31,12 +31,12 @@ function is_running {
 # Start mysqld and block until it comes up.
 function start {
   if ! is_running; then
-    echo "Starting MySQL cartridge"
+    echo "Starting MariaDB cartridge"
     oo-erb conf/my.cnf.erb.hidden > conf/my.cnf
     mysql_context "/usr/bin/mysqld_safe --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.cnf" > /dev/null 2>&1 &
     wait_for_mysqld_availability
   else
-    echo "MySQL already running" 1>&2
+    echo "MariaDB already running" 1>&2
   fi
 }
 
@@ -63,7 +63,7 @@ function stop {
     pidfile=$OPENSHIFT_MARIADB_DIR/pid/mariadb.pid
 
     if [ -f $pidfile ]; then
-      echo "Stopping MySQL cartridge"
+      echo "Stopping MariaDB cartridge"
       pid=$( /bin/cat $pidfile )
       /bin/kill $pid
       ret=$?
@@ -78,9 +78,9 @@ function stop {
       fi
     else
       if `pgrep -x mysqld_safe > /dev/null 2>&1`; then
-        echo "Warning: MySQL process exists without a pid file.  Use force-stop to kill." 1>&2
+        echo "Warning: MariaDB process exists without a pid file.  Use force-stop to kill." 1>&2
       else
-          echo "MySQL already stopped" 1>&2
+          echo "MariaDB already stopped" 1>&2
       fi
     fi
   fi
@@ -88,9 +88,9 @@ function stop {
 
 function status {
   if is_running; then
-    client_result "MySQL is running" 
+    client_result "MariaDB is running" 
   else
-    client_result "MySQL is stopped" 
+    client_result "MariaDB is stopped" 
   fi
 
   exit 0
@@ -166,14 +166,14 @@ function post_restore {
         echo "SET AUTOCOMMIT=1;"
         echo "COMMIT;"
       ) | /usr/bin/mysql -h $OPENSHIFT_MARIADB_DB_HOST -P $OPENSHIFT_MARIADB_DB_PORT -u $OPENSHIFT_MARIADB_DB_USERNAME --password="$OPENSHIFT_MARIADB_DB_PASSWORD" --skip-column-names
-    } || error "Could not import MySQL Database" 187
+    } || error "Could not import MariaDB Database" 187
 
 
     # Grant permissions to the current user
     run_sql "
     GRANT ALL ON *.* TO '$NEW_USER'@'$NEW_IP' IDENTIFIED BY '$OPENSHIFT_MARIADB_DB_PASSWORD' WITH GRANT OPTION;
     GRANT ALL ON *.* TO '$NEW_USER'@'%' IDENTIFIED BY '$OPENSHIFT_MARIADB_DB_PASSWORD' WITH GRANT OPTION;
-    " || error "Could not grant permissions for MySQL database" 187
+    " || error "Could not grant permissions for MariaDB database" 187
 
     # Only run the following if the username is different
     if [ "${OLD_USER}" != "${NEW_USER}" ]
@@ -209,7 +209,7 @@ function post_restore {
 
     cleanup_dump
   else
-    echo "MySQL restore attempted but no dump found!" 1>&2
+    echo "MariaDB restore attempted but no dump found!" 1>&2
     echo "$OPENSHIFT_DATA_DIR/mariadb_dump_snapshot.gz does not exist" 1>&2
   fi
 }
diff --git a/cartridges/openshift-origin-cartridge-mariadb/bin/install b/cartridges/openshift-origin-cartridge-mariadb/bin/install
--- a/cartridges/openshift-origin-cartridge-mariadb/bin/install
+++ b/cartridges/openshift-origin-cartridge-mariadb/bin/install
@@ -8,12 +8,12 @@ case "$1" in
     version="$2"
 esac
 
-# Add OPENSHIFT_MYSQL_VERSION variable to help mysql_context
+# Add OPENSHIFT_MARIADB_VERSION variable to help mysql_context
 # choose the right version. Also need to be exported for install.
 #
-env_dir="${OPENSHIFT_MYSQL_DIR}/env"
-set_env_var 'OPENSHIFT_MYSQL_VERSION' $version $env_dir
-export OPENSHIFT_MYSQL_VERSION=$version
+env_dir="${OPENSHIFT_MARIADB_DIR}/env"
+set_env_var 'OPENSHIFT_MARIADB_VERSION' $version $env_dir
+export OPENSHIFT_MARIADB_VERSION=$version
  
 # Generate username, password, and db name and create env variables
 echo 'Generating username and password'
@@ -35,10 +35,10 @@ echo 'Installing mariadb'
 mariadb_data_dir="${OPENSHIFT_MARIADB_DIR}/data"
 
 # Must be invoked with absolute path to avoid a mariadb bug involving my_print_defaults
-mysql_context "/usr/bin/mysql_install_db --datadir=${mysql_data_dir} --user=${USER}" || error 'Failed to create mysqldb', 119
+mysql_context "/usr/bin/mysql_install_db --datadir=${mariadb_data_dir} --user=${USER}" || error 'Failed to create mariadb database', 119
 
 client_result ""
-client_result "MariaDB ${OPENSHIFT_MYSQL_VERSION} database added.  Please make note of these credentials:"
+client_result "MariaDB ${OPENSHIFT_MARIADB_VERSION} database added.  Please make note of these credentials:"
 client_result ""
 client_result "       Root User: $username"
 client_result "   Root Password: $password"
@@ -47,8 +47,8 @@ client_result ""
 
 client_result 'Connection URL: mysql://$OPENSHIFT_MARIADB_DB_HOST:$OPENSHIFT_MARIADB_DB_PORT/'
 client_result ""
-client_result "You can manage your new MySQL database by also embedding phpmyadmin."
-client_result "The phpmyadmin username and password will be the same as the MySQL credentials above."
+client_result "You can manage your new MariaDB database by also embedding phpmyadmin."
+client_result "The phpmyadmin username and password will be the same as the MariaDB credentials above."
 
 cart_props 'connection_url=mysql://$OPENSHIFT_MARIADB_DB_HOST:$OPENSHIFT_MARIADB_DB_PORT/'
 cart_props "username=$username"
