WIP: v2 mysql

diff --git a/cartridges/openshift-origin-cartridge-mysql/bin/control b/cartridges/openshift-origin-cartridge-mysql/bin/control
--- a/cartridges/openshift-origin-cartridge-mysql/bin/control
+++ b/cartridges/openshift-origin-cartridge-mysql/bin/control
@@ -2,14 +2,15 @@
 
 PATH=/bin/:/usr/bin:$PATH
 
-source env/*
+source $OPENSHIFT_MYSQL_DIR/env/*
 
 function is_running {
   pidfile=$OPENSHIFT_MYSQL_DIR/pid/mysql.pid
 
   if [ -f $pidfile ]; then
     mysql_pid=`cat $pidfile 2> /dev/null`
-    myid=`id -u` 
+    myid=`id -u`
+
     if `ps --pid $mysql_pid > /dev/null 2>&1` || `pgrep -x mysqld_safe -u $myid > /dev/null 2>&1`
     then
       return 0
@@ -23,9 +24,8 @@ function is_running {
 # TODO: source user hooks?
 # Start mysqld and block until it comes up.
 function start {
-  if ! is_running
-  then
-    /usr/bin/mysqld_safe --defaults-file=conf/my.cnf >/dev/null 2>&1 &    
+  if ! is_running; then
+    /usr/bin/mysqld_safe --defaults-file=$OPENSHIFT_MYSQL_DIR/conf/my.cnf > /dev/null 2>&1 &    
     wait_for_mysqld_availability
   else
     echo "MySQL already running" 1>&2
@@ -35,15 +35,14 @@ function start {
 function wait_for_mysqld_availability {
   pidfile=$OPENSHIFT_MYSQL_DIR/pid/mysql.pid
 
-  if [ -n "$OPENSHIFT_MYSQL_DB_USERNAME" ]
-  then
-      i=0
+  if [ -n "$OPENSHIFT_MYSQL_DB_USERNAME" ]; then
+    i=0
+    sleep 1
+    while (( ! touch_mysqld ) || [ ! -f $pidfile ]) && [ $i -lt 30 ]
+    do
       sleep 1
-      while (( ! touch_mysqld ) || [ ! -f $pidfile ]) && [ $i -lt 30 ]
-      do
-          sleep 1
-          i=$(($i + 1))
-      done
+      i=$(($i + 1))
+    done
   fi
 }
 
@@ -67,8 +66,7 @@ function stop {
       done
     fi
   else
-    if `pgrep -x mysqld_safe > /dev/null 2>&1`
-    then
+    if `pgrep -x mysqld_safe > /dev/null 2>&1`; then
       echo "Warning: MySQL process exists without a pid file.  Use force-stop to kill." 1>&2
     else
         echo "MySQL already stopped" 1>&2
@@ -86,9 +84,40 @@ function status {
   exit 0
 }
 
+function handle_setup_marker {
+  setup_marker_file=$OPENSHIFT_TMP_DIR/.setup_invocation_marker
+
+  if [ -f $setup_marker_file ]; then
+    prepare_database
+    rm -f $setup_marker_file   
+  fi
+}
+
+function error {
+    echo "$1" 1>&2
+    exit "$2"
+}
+
+function prepare_database {
+  dbname=$OPENSHIFT_APP_NAME
+  socket_file=$OPENSHIFT_MYSQL_DB_SOCKET
+
+  echo 'Setup marker detected, reconfiguring mysqld'
+
+  echo "drop database test;
+  create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql -u root -S "$socket_file" > /dev/null || error 'Failed to create database', 188
+
+  echo "                                  
+  delete from user;
+  grant all on *.* to '$username'@'$OPENSHIFT_MYSQL_DB_HOST' identified by '$password' with grant option;
+  grant all on *.* to '$username'@'localhost' identified by '$password' with grant option;
+  flush privileges;" | mysql -u root -S "$socket_file" mysql > /dev/null || error "Failed to setup initial root user" 187
+}
+
 case "$1" in
   start)
     start
+    handle_setup_marker
   ;;
   stop)
     stop
diff --git a/cartridges/openshift-origin-cartridge-mysql/bin/setup b/cartridges/openshift-origin-cartridge-mysql/bin/setup
--- a/cartridges/openshift-origin-cartridge-mysql/bin/setup
+++ b/cartridges/openshift-origin-cartridge-mysql/bin/setup
@@ -3,7 +3,7 @@
 # Mock cartridge for testing and verifying node platform code. This is
 # not an example of how to write a well-formed cartridge.
 
-source env/*
+source $OPENSHIFT_HOMEDIR/redhat-mysql/env/*
 
 # The following functions are ripped from v1 abstract util
 
@@ -45,33 +45,30 @@ function error {
     exit "$2"
 }
 
+function drop_setup_marker {
+    touch $OPENSHIFT_TMP_DIR/.setup_invocation_marker
+}
+
+mkdir $OPENSHIFT_MYSQL_DIR/{log,pid,socket,data,run}
+
 # TODO: configure httpd if the app is standalone
 
 # Generate username, password, and db name and create env variables
-# TODO: move username/password into manifest?
+echo 'Generating username and password'
+
 username=$(generate_username)
 password=$(generate_password)
 
-echo "export OPENSHIFT_MYSQL_DB_USERNAME='$username'" > env/OPENSHIFT_MYSQL_DB_USERNAME
-echo "export OPENSHIFT_MYSQL_DB_PASSWORD='$password'" > env/OPENSHIFT_MYSQL_DB_PASSWORD
-echo "export OPENSHIFT_MYSQL_DB_URL='mysql://$username:$password@$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/'" > env/OPENSHIFT_MYSQL_DB_URL
+echo "export OPENSHIFT_MYSQL_DB_USERNAME='$username'" > $OPENSHIFT_MYSQL_DIR/env/OPENSHIFT_MYSQL_DB_USERNAME
+echo "export OPENSHIFT_MYSQL_DB_PASSWORD='$password'" > $OPENSHIFT_MYSQL_DIR/env/OPENSHIFT_MYSQL_DB_PASSWORD
+echo "export OPENSHIFT_MYSQL_DB_URL='mysql://$username:$password@$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/'" > $OPENSHIFT_MYSQL_DIR/env/OPENSHIFT_MYSQL_DB_URL
 
-mysql_install_db --defaults-file=conf/mysql_stub_config --basedir=. --datadir=./data > /dev/null 2>&1
+echo 'Installing mysqld'
 
-if [[ $? -ne 0]]; then
-  error 'Failed to create mysqldb', 119
-fi
+# Must be invoked with absolute path to avoid a mysql bug involving my_print_defaults
+/usr/bin/mysql_install_db --datadir=$OPENSHIFT_MYSQL_DIR/data || error 'Failed to create mysqldb', 119
 
-dbname=$OPENSHIFT_APP_NAME
-
-echo "drop database test;
-create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql -u root -S "${MYSQL_DIR}/socket/mysql.sock" > /dev/null || error 'Failed to create database', 188
-
-echo "                                  
-delete from user;
-grant all on *.* to '$username'@'$OPENSHIFT_MYSQL_DB_HOST' identified by '$password' with grant option;
-grant all on *.* to '$username'@'localhost' identified by '$password' with grant option;
-flush privileges;" | mysql -u root -S "socket/mysql.sock" mysql > /dev/null || error "Failed to setup initial root user" 187
+drop_setup_marker
 
 # client_result (scalable app concerns?)
 cart_props 'connection_url=mysql://$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/'
