Use uft8mb4 to support 4-byte unicode characters
Bug 1186681
https://bugzilla.redhat.com/show_bug.cgi?id=1186681
The utf8 character encoding in mysql supports unicode characters with 1-3 bytes. 4-byte unicode characters such as emojis require utf8mb4 encoding in mysql.

diff --git a/cartridges/openshift-origin-cartridge-mysql/bin/post_install b/cartridges/openshift-origin-cartridge-mysql/bin/post_install
--- a/cartridges/openshift-origin-cartridge-mysql/bin/post_install
+++ b/cartridges/openshift-origin-cartridge-mysql/bin/post_install
@@ -11,7 +11,7 @@ password=$OPENSHIFT_MYSQL_DB_PASSWORD
 # TODO: Should be we running mysql_secure_installation
 
 echo "drop database test;
-create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql_context "/usr/bin/mysql -u root -S '$socket_file'" > /dev/null || error 'Failed to create database' 188
+create database \`${dbname}\` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;" | mysql_context "/usr/bin/mysql -u root -S '$socket_file'" > /dev/null || error 'Failed to create database' 188
 
 echo "
 delete from user;
