Fix bug 981622

diff --git a/cartridges/openshift-origin-cartridge-mysql/bin/post_install b/cartridges/openshift-origin-cartridge-mysql/bin/post_install
--- a/cartridges/openshift-origin-cartridge-mysql/bin/post_install
+++ b/cartridges/openshift-origin-cartridge-mysql/bin/post_install
@@ -1,5 +1,7 @@
 #!/bin/bash -e
 
+source $OPENSHIFT_CARTRIDGE_SDK_BASH
+
 dbname=$OPENSHIFT_APP_NAME
 socket_file=$OPENSHIFT_MYSQL_DB_SOCKET
 username=$OPENSHIFT_MYSQL_DB_USERNAME
@@ -8,7 +10,7 @@ password=$OPENSHIFT_MYSQL_DB_PASSWORD
 # TODO: Should be we running mysql_secure_installation
 
 echo "drop database test;
-create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql -u root -S "$socket_file" > /dev/null || error 'Failed to create database', 188
+create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql -u root -S "$socket_file" > /dev/null || error 'Failed to create database' 188
 
 echo "                                  
 delete from user;
