No need to test state file in the cartridge.

diff --git a/cartridges/openshift-origin-cartridge-ruby/bin/control b/cartridges/openshift-origin-cartridge-ruby/bin/control
--- a/cartridges/openshift-origin-cartridge-ruby/bin/control
+++ b/cartridges/openshift-origin-cartridge-ruby/bin/control
@@ -159,22 +159,12 @@ function _threaddump() {
 
   PID=$(ps -u $(id -u $1) -o pid,command | grep -v grep | grep 'Rack:.*'$1 | awk 'BEGIN {FS=" "}{print $1}')
 
-  if [ "$PID" = "" ]; then
-      _state_file=${OPENSHIFT_HOMEDIR}/app-root/runtime/.state
-      _state=unknown
-      if [ -f "$_state_file" ]; then
-          _state=`cat "$_state_file"`
-      fi
-
-      if [ -f ${OPENSHIFT_RUBY_DIR}/run/stop_lock -o stopped = "$_state" ]; then
-          echo "Application is stopped.  You must start the application and access it by its URL (http://${OPENSHIFT_GEAR_DNS}) before you can take a thread dump."
-      else
-          echo "Application is inactive. Ruby/Rack applications must be accessed by their URL (http://${OPENSHIFT_GEAR_DNS}) before you can take a thread dump."
-      fi
-  else 
-      if ! kill -s ABRT $PID; then
-        echo "Failed to signal application. Please retry after restarting application and access it by its URL (http://${OPENSHIFT_GEAR_DNS})"
-      fi
+  if [ ! "$PID" = "" ]; then
+    echo "Unable to detect application PID. Check the application's availability by accessing http://${OPENSHIFT_GEAR_DNS}"
+  else
+    if ! kill -s ABRT $PID; then
+      echo "Failed to signal application. Please retry after restarting application and access it by its URL (http://${OPENSHIFT_GEAR_DNS})"
+    fi
   fi
 }
 
