Bug 1086691 - Accessing a Gear by ssh shows "Your application is out of disk space" when "quota" command is missing

diff --git a/node/misc/bin/rhcsh b/node/misc/bin/rhcsh
--- a/node/misc/bin/rhcsh
+++ b/node/misc/bin/rhcsh
@@ -80,22 +80,27 @@ function welcome {
 '
   fi
 
-  # Quota returns nonzero if you are over limit
-  if quota >/dev/null 2>&1
+  if which quota  > /dev/null  2>&1
   then
-    local usage=$(quota -w 2>/dev/null| grep '^.*/dev/' | awk '{printf "%3.1f", ($2 / $4 * 100)}')
-    if float_test "$usage > 90.0"
+    # Quota returns nonzero if you are over limit
+    if quota >/dev/null 2>&1
     then
-      echo "Warning: Gear ${OPENSHIFT_GEAR_UUID} is using ${usage}% of disk quota"
-    fi
+      local usage=$(quota -w 2>/dev/null| grep '^.*/dev/' | awk '{printf "%3.1f", ($2 / $4 * 100)}')
+      if float_test "$usage > 90.0"
+      then
+        echo "Warning: Gear ${OPENSHIFT_GEAR_UUID} is using ${usage}% of disk quota"
+      fi
 
-    local usage=$(quota -w 2>/dev/null| grep '^.*/dev/' | awk '{printf "%3.1f",  ($5 / $7 * 100)}')
-    if float_test "$usage > 90.0"
-    then
-      echo "Warning: Gear ${OPENSHIFT_GEAR_UUID} is using ${usage}% of inodes allowed"
+      local usage=$(quota -w 2>/dev/null| grep '^.*/dev/' | awk '{printf "%3.1f",  ($5 / $7 * 100)}')
+      if float_test "$usage > 90.0"
+      then
+        echo "Warning: Gear ${OPENSHIFT_GEAR_UUID} is using ${usage}% of inodes allowed"
+      fi
+    else
+      echo "Your application is out of disk space; please run \"rhc app-tidy $OPENSHIFT_APP_NAME\"" 1>&2
     fi
   else
-    echo "Your application is out of disk space; please run \"rhc app-tidy $OPENSHIFT_APP_NAME\"" 1>&2
+    echo "Command \"quota\" not found for app $OPENSHIFT_APP_NAME, please check the node hosting this app"
   fi
 }
 
