<oo-admin-ctl-cgroups> Bug 964205 - prevent stopping already stopped cgroups
Modified stopuser() to check if the cgroup for the specified user has
already been stopped, and echo a useful message if that is the case
instead running cgdelete and generating "file not found" noise

diff --git a/node/misc/sbin/oo-admin-ctl-cgroups b/node/misc/sbin/oo-admin-ctl-cgroups
--- a/node/misc/sbin/oo-admin-ctl-cgroups
+++ b/node/misc/sbin/oo-admin-ctl-cgroups
@@ -334,12 +334,17 @@ stopuser() {
     #pkill -u $(id -u $_deluser)
 
     # remove the user's cgroup
-    delete_cgroup $_deluser
-    (( _retval |= $? )) # capture return value
+    if cgroup_exists $_deluser
+    then
+        delete_cgroup $_deluser
+        (( _retval |= $? )) # capture return value
 
-    # remove the user's cgroup binding rule
-    delete_cgroup_rule $_deluser
-    (( _retval |= $? )) # capture return value
+        # remove the user's cgroup binding rule
+        delete_cgroup_rule $_deluser
+        (( _retval |= $? )) # capture return value
+    else
+        echo -n " cgroup already stopped"
+    fi
 
     if [ $_retval -eq 0 ]
     then
