Improving oo-admin-ctl-iptables-port-proxy's start method to handle a missing INPUT rule
Previously it would only append the rule. However, if it was after a REJECT
rule then it wouldn't take affect.

diff --git a/node/misc/sbin/oo-admin-ctl-iptables-port-proxy b/node/misc/sbin/oo-admin-ctl-iptables-port-proxy
--- a/node/misc/sbin/oo-admin-ctl-iptables-port-proxy
+++ b/node/misc/sbin/oo-admin-ctl-iptables-port-proxy
@@ -42,11 +42,11 @@ check_firewall() {
     iptables -L | grep 'rhc-app-comm  all' >/dev/null 2>&1
     RETVAL=$?
     if [ ! $RETVAL -eq 0 ]; then
-        echo "ERROR: rhc-app-comm chain not found.  Check /etc/sysconfig/iptables." 1>&2
+        echo "ERROR: rhc-app-comm INPUT rule not found.  Check /etc/sysconfig/iptables." 1>&2
         if [ $FALLBACK ]; then
             iptables -N rhc-app-comm
-            iptables -A INPUT -j rhc-app-comm
-            echo "WARNING: The chain has been temporarily added."
+            iptables -I INPUT 1 -j rhc-app-comm
+            echo "WARNING: The INPUT rule has been temporarily added."
         else
             exit 1
         fi
